[project]
name = "recruitment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "amqp==5.3.1",
    "asgiref==3.8.1",
    "attrs==24.3.0",
    "autobahn==24.4.2",
    "automat==24.8.1",
    "billiard==4.2.1",
    "celery==5.4.0",
    "certifi==2024.12.14",
    "cffi==1.17.1",
    "channels==4.2.0",
    "charset-normalizer==3.4.1",
    "click==8.1.8",
    "click-didyoumean==0.3.1",
    "click-plugins==1.1.1",
    "click-repl==0.3.0",
    "constantly==23.10.4",
    "crispy-tailwind==1.0.3",
    "cryptography==44.0.0",
    "daphne==4.1.2",
    "diff-match-patch==20241021",
    "django==5.1.4",
    "django-allauth==65.3.1",
    "django-appconf==1.0.6",
    "django-cleanup==9.0.0",
    "django-cotton==1.5.1",
    "django-cotton-components>=0.1.6",
    "django-crispy-forms==2.3",
    "django-environ==0.11.2",
    "django-extensions==3.2.3",
    "django-filter==24.3",
<<<<<<< HEAD
    "django-guardian==2.4.0",
=======
>>>>>>> upstream/main
    "django-import-export==4.3.3",
    "django-phonenumber-field==8.0.0",
    "django-recaptcha==4.0.0",
    "django-tinymce==4.1.0",
    "django-unfold==0.46.0",
    "django-widget-tweaks==1.5.0",
    "djangorestframework==3.15.2",
    "djhtml==3.0.7",
    "flower==2.0.1",
    "gunicorn==23.0.0",
    "humanize==4.11.0",
    "hyperlink==21.0.0",
    "idna==3.10",
    "incremental==24.7.2",
    "isort==5.13.2",
    "jinja2==3.1.5",
    "kombu==5.4.2",
    "markdown==3.7",
    "markupsafe==3.0.2",
    "packaging==24.2",
    "phonenumbers==8.13.52",
    "pillow==11.1.0",
    "pip-review==1.3.0",
    "prometheus-client==0.21.1",
    "prompt-toolkit==3.0.48",
    "psycopg2-binary==2.9.10",
    "pyasn1==0.6.1",
    "pyasn1-modules==0.4.1",
    "pycparser==2.22",
    "pyopenssl==24.3.0",
    "pytest-django>=4.9.0",
    "python-dateutil==2.9.0.post0",
    "pytz==2024.2",
    "rcssmin==1.2.0",
    "redis==5.2.1",
    "requests==2.32.3",
    "rjsmin==1.2.3",
    "service-identity==24.2.0",
    "setuptools==75.6.0",
    "six==1.17.0",
    "sqlparse==0.5.3",
    "tablib==3.7.0",
    "tornado==6.4.2",
    "twisted==24.11.0",
    "txaio==23.1.1",
    "typing-extensions==4.12.2",
    "tzdata==2024.2",
    "urllib3==2.3.0",
    "vine==5.1.0",
    "wcwidth==0.2.13",
    "whitenoise==6.8.2",
    "zope-interface==7.2",
]

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = ["F","E","W","I","N","R"]
extend-ignore = ["F403"]

[dependency-groups]
dev = [
    "django-browser-reload>=1.17.0",
    "django-debug-toolbar>=5.0.1",
    "ruff>=0.9.5",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings.development"
<<<<<<< HEAD
python_files = ["test_*.py", "*_test.py", "tests.py","tests/"]
=======
python_files = ["test_*.py", "*_test.py", "tests.py","tests/"]
>>>>>>> upstream/main
